### ISSUE TITLE
X Gantry Cable Box Bottom Poor Side Wall Extrusion

### ISSUE THREAD

**Issue by safetychief8** [OmNomNomagon/ReDuplicator-MK2sx#1]
There's poor extrusion in the walls of the X gantry cable box bottom. I loaded into S3D, and output the gcode file. The other items are printing without issue. Please check to see if there's an issue with the code. Tried to print it 3 times with tweaks in the settings, but had the same result.  Also, you show various washers in the pictures, but you don't mention them in the bill of materials. Are washers necessary?

**Comment by OmNomNomagon** [comment]
In S3D what are your thin wall behavior settings?
I've got it setup as:

External Thin Wall: Perimeters Only
Internal Thin Wall: Allow Gap Fill
Allowed Perimeter Overlap: 20% 

Can you give me a more detailed description or a pic? Does it show up in the layer previews? I checked, it looks okay in mine but If it persists I'll bump the wall thicknesses by 0.5mm, which should fix it up.

With regards to washers, the only part that may need them is the X motor mount, and only if you use neoprene washers to try to decouple the motor from the frame. I'll update the wiki to clarify.

**Comment by safetychief8** [comment]
Hello,

With regards to printing, it only seems to be that one part for some reason, all the others print fine, that's why I suggested that that code or print settings may be suspect. I'll look to purchase the washers for the appropriate sized screws, thanks.



Sent via the Samsung Galaxy S8, an AT&T 4G LTE smartphone


-------- Original message --------
From: OmNomNomagon <notifications@github.com>
Date: 1/17/18 5:26 AM (GMT-05:00)
![20180119_025156](https://user-images.githubusercontent.com/17696106/35140184-513c2ae8-fcc4-11e7-825d-a4618fda3f51.jpg)
![20180119_025213](https://user-images.githubusercontent.com/17696106/35140189-553c9c54-fcc4-11e7-910e-95eb6a4ae5f3.jpg)
![20180119_025228](https://user-images.githubusercontent.com/17696106/35140195-5897948a-fcc4-11e7-943f-93cc69bf24ad.jpg)
![20180119_025213](https://user-images.githubusercontent.com/17696106/35140246-8aaa3fe0-fcc4-11e7-8cf8-ba4703fda5d3.jpg)
![20180119_025228](https://user-images.githubusercontent.com/17696106/35140247-8ab7daba-fcc4-11e7-8233-a913a4fadb6e.jpg)
![20180119_025156](https://user-images.githubusercontent.com/17696106/35140248-8ac2fff8-fcc4-11e7-86ec-d4777b64a5c7.jpg)






To: OmNomNomagon/ReDuplicator-MK2sx <ReDuplicator-MK2sx@noreply.github.com>
Cc: safetychief8 <sjharbin@hotmail.com>, Author <author@noreply.github.com>
Subject: Re: [OmNomNomagon/ReDuplicator-MK2sx] X Gantry Cable Box Bottom Poor Side Wall Extrusion (#1)

SDHC SD Card Reader Extension Cable KZ-B19 FPC UNIVERSAL Flash Memory Card Extension Cable
In S3D what are your thin wall behavior settings?
I've got it setup as:

External Thin Wall: Perimeters Only
Internal Thin Wall: Allow Gap Fill
Allowed Perimeter Overlap: 20%

Dan you give me a more detailed description or a pic? Does it show up in the layer previews? I checked, it looks okay in mine but If it persists I'll bump the wall thicknesses by 0.5mm, which should fix it up.

With regards to washers, the only part that may need them is the X motor mount, and only if you use neoprene washers to try to decouple the motor from the frame. I'll update the wiki to clarify.

**Comment by safetychief8** [comment]
I've attached some pictures of the extruded part.

![20180119_025228](https://user-images.githubusercontent.com/17696106/35140346-e809ec3a-fcc4-11e7-8b34-be3b38f775e1.jpg)
![20180119_025213](https://user-images.githubusercontent.com/17696106/35140363-f2965e2c-fcc4-11e7-8fb7-a52548afee95.jpg)
![20180119_025156](https://user-images.githubusercontent.com/17696106/35140377-fc73605c-fcc4-11e7-8306-dc22c8c7049d.jpg)

**Comment by OmNomNomagon** [comment]
Oh wow, don't think its an issue with the file. Is this PETG? It looks like maybe you need to dial up the temps a bit reduce your retractions and maybe increase your extrusion modifier a tad.

**Comment by safetychief8** [comment]
It’s PLA, all the other parts extruded ok with the same material and settings.

Sent from my iPad

On Jan 21, 2018, at 9:16 AM, OmNomNomagon <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh wow, don't think its an issue with the file. Is this PETG? It looks like maybe you need to dial up the temps a bit and maybe increase your extrusion modifier a tad.

**Comment by OmNomNomagon** [comment]
![img_20180122_161617](https://user-images.githubusercontent.com/7193108/35206337-10e05efa-ff90-11e7-98a2-7a1b1a36b974.jpg)

I printed another one out super quick with no issues. 
Id say this is an issue with your printer that is only showing up on parts with thinner or finer details. I used to have a similar problem with certain types of petg. Without knowing more about your setup, reckon you should check the following.
- Double check your extruder drive gear is not loose or clogged,
- is your fan aimed to high? if the part fan is cooling your heater block it could cause these sorts of issues. Try reducing fan speed.
- double check your esteps https://3dprinterwiki.info/extruder-steps/
- retraction might be too high, causing melted plastic to move too far past the heatbreak, It would cause issues specifically on thinner prints with more retractions. try reducing this.
- Bump up your temperature 
- Bump up your extrusion multiplier
- might just be bad or inconsistent filament

Please let me know if you have any luck with this.

**Comment by safetychief8** [comment]
Thanks, I'll try them, just set up the Maker V2, I'll try it on that printer instead of the delta.
