### ISSUE TITLE
Printed parts don’t fit with Misumi T-Nuts

### ISSUE THREAD

**Issue by Abai** [OmNomNomagon/ReDuplicator-MK2sx#12]
![347F5F54-FE5D-41EC-A577-AC8BCA48A4A5](https://user-images.githubusercontent.com/592671/89561761-44e71b80-d819-11ea-9dd6-c05f40b09823.jpeg)
![BAB2AAF4-DA24-4D33-8498-9C4D84600259](https://user-images.githubusercontent.com/592671/89561774-49133900-d819-11ea-8517-b08fb9cb0e16.jpeg)

The printed parts that attach to extrusions are tabbed. So are the Misumi T-nuts. The slots in the printed parts tabs, need to be 14mm wide, 7mm on each side of the screw hole center.

I saw that you created a new revision of parts two days ago. Very cool! I would like to fix these before reprinting. Could you please provide the fusion 360 files? This change should not cause any issues when using non-tabbed t-nuts like you do, so I can also make a pull request with fixed STL’s if you like.

Thanks!

**Comment by Abai** [comment]
Alternative to making 14mm slots in printed tabs, it is possible to make all printed tabs 1mm high maximum. This is what misumi does with the tabs of their corner brackets.

Here are the drawings:

![D1C47A1D-B9FF-4C97-A8DF-A85E40615D0C](https://user-images.githubusercontent.com/592671/89567949-dc9d3780-d822-11ea-9af8-f08b40e3cc7a.jpeg)
![FA714DD4-6A30-47DF-AB1A-1A991ABB937B](https://user-images.githubusercontent.com/592671/89567952-deff9180-d822-11ea-8ea7-e5d9dceb70bd.jpeg)
![104116FA-9EAB-430F-BF76-D55FF8566AA4](https://user-images.githubusercontent.com/592671/89567955-df982800-d822-11ea-851c-169f921eee85.jpeg)

**Comment by OmNomNomagon** [comment]
Hi mate, sorry you are having issues. M5 drop in T-nuts were always the preferred and recommended part for all the printed parts.  I recommend that you switch to drop in nuts for the printed parts and use the misumi ones for all the other structural parts.
