### ISSUE TITLE
MK52 Expansion X Gantry measuremements

### ISSUE THREAD

**Issue by Abai** [OmNomNomagon/ReDuplicator-MK2sx#13]
On MK52 expansion wiki you mention:

“ The 380mm rods are mounted on the Y axis, 330mm rods on the z axis and 370 rods in the Y axis”

You mention Y twice here.

I assume 370 rod is for X gantry and 380 for Y axis.

If the above is correct, then the BOM table on the same page should also be updated.

**Comment by OmNomNomagon** [comment]
Thanks Mate

you are correct, the lengths are:

new rods
x axis: 370mm
existing wanhao rods
Z Axis: 330mm
Y Axis: 380mm
