### ISSUE TITLE
Guidance for fresh build

### ISSUE THREAD

**Issue by DJdaSilva** [OmNomNomagon/ReDuplicator-MK2sx#19]
Hello there! @OmNomNomagon 

So I am looking through this repository, keen to build this bad boy!

I realize it is an upgrade over the wanhao i3, actually a total overhaul! I'm really keen to build the full project from scratch, but obviously since I don't have the original printer there are some challenges.... so I guess I am looking for a little guidance on the original printer, small details like stepper motors and electronics etc. Perhaps you know of a clone that would play well with your upgrades? It seems like the wanhao i3 isn't a thing anymore? Am I crazy for wanting to do this as a beginner? I have access to prusa parts so was wondering if their software and electronics could be used with your upgrades to any degree? Anyway sorry lots of questions but any general guidance appreciated!

PS. Thanks for making this public I think it looks amazing!

**Comment by OmNomNomagon** [comment]
Hi DJdaSilva,

thanks for your interest in this project. This project can be quite complex if you are not using a Wanhao i3 as a starting point, especially if it is your first build. An alternate option is to start with a Prusa MK3s or clone and do the Zaribo mod. 

If you would like to do this project from scratch you will need everything in the build logs along with motors, control board, wiring, and heatbed and a hotend/extruder. I can put together a list together if it is something you would like to persue
