### ISSUE TITLE
Y carriage base

### ISSUE THREAD

**Issue by maltitco** [OmNomNomagon/ReDuplicator-MK2sx#3]
Where I can find a dxf and information from which material to cut Y carriage base?

**Comment by OmNomNomagon** [comment]
The Y carriage plate was carried over from the original Wanhao. My particular plate was a lighter aftermarket on as the original was prone to warping. it was purchased via http://tehnologika.net/ although the site appears to be down at the moment. It is an Alu Melamine composite. Any Wanhao compatible Y-plate will work. There are a number of alternatives.

Here is a dxf source.
https://www.thingiverse.com/thing:1708260

If cutting from aluminium a thickness of 3mm - 4mm should give you the desired stiffness at the lowest weight.
