### ISSUE TITLE
Titan Aero part Cooling Fan Mount.stl has too thin walls

### ISSUE THREAD

**Issue by MarMed** [OmNomNomagon/ReDuplicator-MK2sx#4]
Titan Aero part Cooling Fan Mount.stl has too thin walls where the heat serts holes are, resulting in a slicing error.

**Comment by OmNomNomagon** [comment]
Okay, I'll take a look

**Comment by OmNomNomagon** [comment]
It appears at some points the walls are too thin to print with a .4mm nozzle, however the part is still strong and functional and still accepts the heat serts. I'll try to redesign this part but this area in particular is very narrow and may not be possible

**Comment by OmNomNomagon** [comment]
I've redesigned the cooler to a Prusa MK3 one, which makes better use of the space under the extruder. It also performs much better than the original Thorped one. I have it uploaded soon.

**Comment by OmNomNomagon** [comment]
New MK3 Fan shroud has been uploaded :) . It has much better spacing in this area, by incorporating the shroud and bracket into one.
