### ISSUE TITLE
Y-carriage bearing blocks are not listed under the 'multiple copies required' summary in section 2

### ISSUE THREAD

**Issue by ddcunningham** [OmNomNomagon/ReDuplicator-MK2sx#6]
The Y carriage bearing block STL only has one Y carriage included in it, but is not listed under the 'multiple parts required' summary.  If one follows sections 1 and 2, they will be short 2 bearing blocks.

**Comment by OmNomNomagon** [comment]
thanks mate, wiki has been updated.
