### ISSUE TITLE
BOM missing M2 heat-serts for Y Axis Idler?

### ISSUE THREAD

**Issue by beriberikix** [OmNomNomagon/ReDuplicator-MK2sx#7]
[Section 3.](https://github.com/OmNomNomagon/ReDuplicator-MK3x/wiki/3.-Base) states that the  Y Axis Idler needs 2x M2 heat-serts inserted on the front. I haven't built this yet but if that's correct, should M2 heat-serts be added to the [BOM](https://github.com/OmNomNomagon/ReDuplicator-MK3x/wiki/1.--Bill-Of-Materials)?

**Comment by OmNomNomagon** [comment]
Thanks for bringing this up. its a spelling mistake. These parts are M3 heatserts and are already included in the bom total. I've updated the pages.
