### ISSUE TITLE
BOM missing M3ns for X Gantry Motor Mount MK3 V2?

### ISSUE THREAD

**Issue by beriberikix** [OmNomNomagon/ReDuplicator-MK2sx#8]
[Section 7.](https://github.com/OmNomNomagon/ReDuplicator-MK3x/wiki/7.-Complete--the-ZTower) states that the X Gantry Motor Mount MK3 V2 needs a M3ns, though the changelog says it is optional. I haven't built this yet but if that's correct, should a M3ns be added to the [BOM](https://github.com/OmNomNomagon/ReDuplicator-MK3x/wiki/1.--Bill-Of-Materials)?

**Comment by OmNomNomagon** [comment]
Thanks mate, i added them to the BOM. I skipped over them originally as I couldn't source these parts.
